In [39]:
import os
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
import joblib

In [40]:
df = pd.read_csv(r"..\data\raw\WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(2)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No

In [41]:
df.drop('customerID',axis=1,inplace=True)

In [42]:
cat_col = df.select_dtypes(include='string').columns.to_list()

### No need to labelEncode the Target column as it is binary | we will just replace

In [43]:
df['Churn'] = df["Churn"].replace({'Yes':1,'No':0})
df.head(2)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,0

In [44]:
df.Churn.value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [45]:
encoders={}

for col in cat_col:
    labelEn = LabelEncoder()
    df[col] = labelEn.fit_transform(df[col])
    encoders[col] = labelEn

with open("../models/encoder.pkl","wb") as f:
    joblib.dump(encoders,f)

In [46]:
for col in df.columns:
    print(col)
    print(df[col].unique())
    print('-'*50)

gender
[0 1]
--------------------------------------------------
SeniorCitizen
[0 1]
--------------------------------------------------
Partner
[1 0]
--------------------------------------------------
Dependents
[0 1]
--------------------------------------------------
tenure
[ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26  0
 39]
--------------------------------------------------
PhoneService
[0 1]
--------------------------------------------------
MultipleLines
[1 0 2]
--------------------------------------------------
InternetService
[0 1 2]
--------------------------------------------------
OnlineSecurity
[0 2 1]
--------------------------------------------------
OnlineBackup
[2 0 1]
--------------------------------------------------
DeviceProtection
[0 2 1]
--------------------------------------------------
TechSupport
[0 2 1]
--------------------------------------------------
StreamingTV
[0 2 1]
--------------------------------------------------
StreamingMovies
[0 2 1]
--------------------------------------------------
Contract
[0 1 2]
--------------------------------------------------
PaperlessBilling
[1 0]
--------------------------------------------------
PaymentMethod
[2 3 0 1]
--------------------------------------------------
MonthlyCharges
[29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
--------------------------------------------------
TotalCharges
[2505 1466  157 ... 2994 2660 5407]
--------------------------------------------------
Churn
[0 1]
--------------------------------------------------

In [47]:
df.to_csv("../data/processed/customer.csv",index=False)